using Blazored.LocalStorage;
using Blazored.Toast;
using HRMClient;
using HRMClient.Services;
using Microsoft.AspNetCore.Components.Authorization;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Syncfusion.Blazor;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

builder.Services.AddSyncfusionBlazor();
//builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri("https://localhost:7173") });
builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri("https://localhost:44341") });
builder.Services.AddAntDesign();
builder.Services.AddAutoMapper(typeof(AutoMapperProfiles).Assembly);
builder.Services.AddBlazoredLocalStorage();
builder.Services.AddBlazoredToast();
builder.Services.AddScoped<AuthenticationStateProvider, ApiAuthenticationStateProvider>();
builder.Services.AddScoped<IAuthService, AuthService>();
builder.Services.AddScoped<IUserService, UserService>();
builder.Services.AddScoped<ICompanyService, CompanyService>();
builder.Services.AddScoped<IDepartmentService, DepartmentService>();
builder.Services.AddScoped<IPositionService, PositionService>();
builder.Services.AddScoped<ITeamService, TeamService>();
builder.Services.AddScoped<IRoleService, RoleService>();
builder.Services.AddScoped<ILaborContractService, LaborContractService>();
builder.Services.AddScoped<ITimekeepingService, TimekeepingService>();
builder.Services.AddScoped<IMonthTimekeepingService, MonthTimekeepingService>();
builder.Services.AddScoped<IWageTypeService, WageTypeService>();
builder.Services.AddSingleton<DragDropManager>();
await builder.Build().RunAsync();
